services:
  develop:
    build: ./docker/develop
    ports:
      - "8000:8000"
    volumes:
      - ./:/srv/project:cached
    networks:
      - default
    secrets:
      - user_ssh_key

secrets:
  user_ssh_key:
    file: ~/.ssh/id_rsa
